### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by ghost** [vedovelli/expenses-native#2]
Só precisei rodar os seguites comandos:  

sudo sysctl -w kern.maxfiles=5242880
sudo sysctl -w kern.maxfilesperproc=524288

**Comment by caiquecastro** [comment]
Por que você precisou rodar esses comandos? @juscilan

**Comment by vedovelli** [comment]
@juscilan  Também fiquei curioso! 

Qual o SO?!

Qual a necessidade disso?! =D

**Comment by ghost** [comment]
Mac, provavelmente alguma limitação do SO resolvi documentar, aparentemente nada relativo ao projeto ou suas dependências...  =)
